import { Testimonial } from "./type";
export const testimonials: Testimonial[] = [
  {
    text: "“The services was exceptional! From start to finish , the team made the process smooth and stress-free. I found the perfect place to call home, and i couldn’t be happier.”",
    name: "Abdulkadir Hamarow",
    role: "Customer",
    image: "/avater-1.png",
  },
  {
    text: "“The services was exceptional! From start to finish , the team made the process smooth and stress-free. I found the perfect place to call home, and i couldn’t be happier.”",
    name: "Ruka Oyefeso",
    role: "Customer",
    image: "/avater-2.png",
  },
  {
    text: "“The services was exceptional! From start to finish , the team made the process smooth and stress-free. I found the perfect place to call home, and i couldn’t be happier.”.",
    name: "Kolapo Ayodele",
    role: "Customer",
    image: "/avater-3.png",
  },
];

export const imagees = [
  "/afforable-1.png",
  "/afforable-2.png",
  "/house1.png",
  "/house1.png",
  ,
];

export const properties = [
  { imageSrc: "/house1.png", altText: "rent1", price: "18,000.00", area: "" },
  { imageSrc: "/house-3.png", altText: "rent2", price: "20,000.00", area: "" },
  { imageSrc: "/rent3.png", altText: "rent3", price: "22,000.00", area: "" },
  { imageSrc: "/rent4.png", altText: "rent4", price: "24,000.00", area: "" },
  { imageSrc: "/rent5.png", altText: "rent5", price: "26,000.00", area: "" },
  { imageSrc: "/rent6.png", altText: "rent6", price: "28,000.00", area: "" },
];

export const articles = [
  /* eslint-disable */
  {
    id: "19",
    imageSrc: "/article-image/19.png",
    altText:
      "Rental Scams Uncovered: How to Spot and Avoid Fraudulent Listings",
    articleType: "General",
    title: "Rental Scams Uncovered: How to Spot and Avoid Fraudulent Listings",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "20",
    imageSrc: "/article-image/20.png",
    altText: "Will I Be Displayed as the Listing Agent for My Properties?",
    articleType: "Listing inquiries",
    title: "Will I Be Displayed as the Listing Agent for My Properties?",
    readTime: "2 min read",
    date: "March 05, 2025",
  },
  {
    id: "21",
    imageSrc: "/article-image/21.png",
    altText: 'What Does "Sold" Mean in Real Estate?',
    articleType: "General",
    title: 'What Does "Sold" Mean in Real Estate?',
    readTime: "1 min read",
    date: "March 28, 2025",
  },
  {
    id: "22",
    imageSrc: "/article-image/22.png",
    altText: "Viewing Photos of a Property Listing",
    articleType: "Listing Features",
    title: "Viewing Photos of a Property Listing",
    readTime: "2 min read",
    date: "January 05, 2025",
  },
  {
    id: "23",
    imageSrc: "/article-image/23.png",
    altText: "What Are Common Mistakes to Avoid When Buying a Home?",
    articleType: "General",
    title: "What Are Common Mistakes to Avoid When Buying a Home?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "24",
    imageSrc: "/article-image/24.png",
    altText: "How Do I Set the Right Price for My Home?",
    articleType: "General",
    title: "How Do I Set the Right Price for My Home?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "1",
    imageSrc: "/article-image/1.png",
    altText: "How Do I Search for Homes in a Specific Neighborhood?",
    articleType: "General",
    title: "How Do I Search for Homes in a Specific Neighborhood?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "2",
    imageSrc: "/article-image/2.png",
    altText: "How Do I Save My Favorite Listings?",
    articleType: "General",
    title: "How Do I Save My Favorite Listings?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "3",
    imageSrc: "/article-image/3.png",
    altText: "Do I Need a Real Estate Agent to Buy a Home?",
    articleType: "General",
    title: "Do I Need a Real Estate Agent to Buy a Home?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "4",
    imageSrc: "/article-image/4.png",
    altText: "What Do I Do If a Listing Has Incorrect Information?",
    articleType: "General",
    title: "What Do I Do If a Listing Has Incorrect Information?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "5",
    imageSrc: "/article-image/5.png",
    altText: "How Do I Get Alerts for New Listings?",
    articleType: "General",
    title: "How Do I Get Alerts for New Listings?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "6",
    imageSrc: "/article-image/6.png",
    altText: "How Do I Report a Problem With a Listing?",
    articleType: "General",
    title: "How Do I Report a Problem With a Listing?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "7",
    imageSrc: "/article-image/7.png",
    altText:
      "Essential Tips for Writing an Irresistible Property Description...",
    articleType: "General",
    title: "Essential Tips for Writing an Irresistible Property Description...",
    readTime: "3 min read",
    date: "March 15, 2025",
  },
  {
    id: "8",
    imageSrc: "/article-image/8.png",
    altText: "How to Invite Friends to Join Hoydoon.",
    articleType: "Listing Inquiries",
    title: "How to Invite Friends to Join Hoydoon.",
    readTime: "2 min read",
    date: "March 08, 2025",
  },
  {
    id: "9",
    imageSrc: "/article-image/9.png",
    altText: "What Safety Precautions Should I Take When Visiting a Property?",
    articleType: "Listing features",
    title: "What Safety Precautions Should I Take When Visiting a Property?",
    readTime: "1 min read",
    date: "March 28, 2025",
  },
  {
    id: "10",
    imageSrc: "/article-image/10.png",
    altText: "What to Do If You Forget Your Login Details",
    articleType: "Listing features",
    title: "What to Do If You Forget Your Login Details",
    readTime: "2 min read",
    date: "January 08, 2025",
  },
  {
    id: "11",
    imageSrc: "/article-image/11.png",
    altText: "Exploring the Features of the Hoydoon App: A Beginner's Guide",
    articleType: "General",
    title: "Exploring the Features of the Hoydoon App: A Beginner's Guide",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "12",
    imageSrc: "/article-image/12.png",
    altText: "Understanding Hoydoon's Community Guidelines",
    articleType: "General",
    title: "Understanding Hoydoon's Community Guidelines",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "13",
    imageSrc: "/article-image/13.png",
    altText: "Six Small Changes That Increase Your Home's Value by Thousands",
    articleType: "General",
    title: "Six Small Changes That Increase Your Home's Value by Thousands",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "14",
    imageSrc: "/article-image/14.png",
    altText: "Guide to Property Types: Apartments, Houses, Bungalows...",
    articleType: "General",
    title: "Guide to Property Types: Apartments, Houses, Bungalows...",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "15",
    imageSrc: "/article-image/15.png",
    altText: "How to Report Inappropriate Messages or User Behavior",
    articleType: "General",
    title: "How to Report Inappropriate Messages or User Behavior",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "16",
    imageSrc: "/article-image/16.png",
    altText: "How to Update or Edit Your Listing on Hoydoon",
    articleType: "General",
    title: "How to Update or Edit Your Listing on Hoydoon",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "17",
    imageSrc: "/article-image/17.png",
    altText: "Understanding the Difference Between Active, Inactive, and Sold",
    articleType: "General",
    title: "Understanding the Difference Between Active, Inactive, and Sold",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
  {
    id: "18",
    imageSrc: "/article-image/18.png",
    altText: "How Do I Report a Problem With a Listing?",
    articleType: "General",
    title: "How Do I Report a Problem With a Listing?",
    readTime: "3 min read",
    date: "March 13, 2025",
  },
];

export const highlights = [
  { icon: "/solar.png", text: "Solar power system" },
  { icon: "/walkin.png", text: "Walk-in closet" },
  { icon: "/garage.png", text: "Garage parking" },
  { icon: "/balcony.png", text: "Balcony" },
  { icon: "/patio.png", text: "Covered patio or porch" },
  { icon: "/laundry.png", text: "Laundry" },
  { icon: "/pet.png", text: "Pet allowed" },
  { icon: "/heating.png", text: "Heating available" },
];

export const agents = [
  {
    image: "/ruka.jpg",
    name: "Ruka Oyefeso",
    estate: "Mapplewood Estate",
    priceRange: "$500k - $2.5M",
    sales: "20",
  },
  {
    image: "/ruka.jpg",
    name: "Ruka Oyefeso",
    estate: "Mapplewood Estate",
    priceRange: "$500k - $2.5M",
    sales: "20",
  },
  {
    image: "/ruka.jpg",
    name: "Ruka Oyefeso",
    estate: "Mapplewood Estate",
    priceRange: "$500k - $2.5M",
    sales: "20",
  },
  {
    image: "/ruka.jpg",
    name: "Ruka Oyefeso",
    estate: "Mapplewood Estate",
    priceRange: "$500k - $2.5M",
    sales: "20",
  },
  {
    image: "/ruka.jpg",
    name: "Ruka Oyefeso",
    estate: "Mapplewood Estate",
    priceRange: "$500k - $2.5M",
    sales: "20",
  },
  {
    image: "/ruka.jpg",
    name: "Ruka Oyefeso",
    estate: "Mapplewood Estate",
    priceRange: "$500k - $2.5M",
    sales: "20",
  },
];
