FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build arguments for environment variables
ARG NEXT_FACEBOOK_ID
ARG NEXT_FACEBOOK_SECRET
ARG NEXT_GOOGLES_MAP_ID
ARG NEXT_GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_DISTANCE_API_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GOOGLE_REDIRECT_URI
ARG NEXT_MAILCHIMP_API_KEY
ARG NEXT_MAILCHIMP_API_SERVER
ARG NEXT_MAILCHIMP_AUDIENCE_ID
ARG NEXT_PUBLIC_BASE_URL
ARG EMAIL_USERNAME
ARG EMAIL_PASSWORD
ARG NEXT_APPLE_KEY_ID
ARG NEXT_APPLE_TEAM_ID
ARG NEXT_APPLE_ID
ARG NEXTAUTH_SECRET
ARG NEXT_APPLE_PRIVATE_KEY
ARG NEXTAUTH_URL

ENV NEXT_FACEBOOK_ID=$NEXT_FACEBOOK_ID
ENV NEXT_FACEBOOK_SECRET=$NEXT_FACEBOOK_SECRET
ENV NEXT_GOOGLES_MAP_ID=$NEXT_GOOGLES_MAP_ID
ENV NEXT_GOOGLE_CLIENT_SECRET=$NEXT_GOOGLE_CLIENT_SECRET
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_DISTANCE_API_KEY=$NEXT_PUBLIC_GOOGLE_DISTANCE_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_REDIRECT_URI=$NEXT_PUBLIC_GOOGLE_REDIRECT_URI
ENV NEXT_MAILCHIMP_API_KEY=$NEXT_MAILCHIMP_API_KEY
ENV NEXT_MAILCHIMP_API_SERVER=$NEXT_MAILCHIMP_API_SERVER
ENV NEXT_MAILCHIMP_AUDIENCE_ID=$NEXT_MAILCHIMP_AUDIENCE_ID
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV EMAIL_USERNAME=$EMAIL_USERNAME
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV NEXT_APPLE_KEY_ID=$NEXT_APPLE_KEY_ID
ENV NEXT_APPLE_TEAM_ID=$NEXT_APPLE_TEAM_ID
ENV NEXT_APPLE_ID=$NEXT_APPLE_ID
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXT_APPLE_PRIVATE_KEY=$NEXT_APPLE_PRIVATE_KEY
ENV NEXTAUTH_URL=$NEXTAUTH_URL

# Build Next.js application
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy built application
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy process manager
COPY --chown=nextjs:nodejs process-manager.js ./

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "process-manager.js"]
