name: App Service Code

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: hoydoon-web-app

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: npm install and build
              run: |
                  npm ci
                  npm run build
              env:
                  # Facebook Authentication
                  NEXT_FACEBOOK_ID: ${{ secrets.NEXT_FACEBOOK_ID }}
                  NEXT_FACEBOOK_SECRET: ${{ secrets.NEXT_FACEBOOK_SECRET }}
                  # Google Maps & Services
                  NEXT_GOOGLES_MAP_ID: ${{ secrets.NEXT_GOOGLES_MAP_ID }}
                  NEXT_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_GOOGLE_CLIENT_SECRET }}
                  NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                  NEXT_PUBLIC_GOOGLE_DISTANCE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_DISTANCE_API_KEY }}
                  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
                  NEXT_PUBLIC_GOOGLE_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI }}
                  # Mailchimp Configuration
                  NEXT_MAILCHIMP_API_KEY: ${{ secrets.NEXT_MAILCHIMP_API_KEY }}
                  NEXT_MAILCHIMP_API_SERVER: ${{ secrets.NEXT_MAILCHIMP_API_SERVER }}
                  NEXT_MAILCHIMP_AUDIENCE_ID: ${{ secrets.NEXT_MAILCHIMP_AUDIENCE_ID }}
                  # Base URL
                  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
                  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
                  # Apple Authentication
                  NEXT_APPLE_KEY_ID: ${{ secrets.NEXT_APPLE_KEY_ID }}
                  NEXT_APPLE_TEAM_ID: ${{ secrets.NEXT_APPLE_TEAM_ID }}
                  NEXT_APPLE_ID: ${{ secrets.NEXT_APPLE_ID }}
                  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                  NEXT_APPLE_PRIVATE_KEY: ${{ secrets.NEXT_APPLE_PRIVATE_KEY }}
                  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

            - name: Copy static files
              run: |
                  cp -R ./public ./.next/standalone/public
                  cp -R ./.next/static ./.next/standalone/.next/static

            - name: Create startup script
              run: |
                  echo "node server.js" > ./.next/standalone/startup.txt

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: app
                  path: ./.next/standalone

    deploy:
        runs-on: ubuntu-latest
        needs: build

        environment:
            name: production
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: app

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  slot-name: "Production"
                  publish-profile: ${{ secrets.APP_SERVICE_PUBLISH_PROFILE }}
                  package: .
